### PR TITLE
Implementing a CLI

### PR DESCRIPTION
**Pull request by anthonymonori**
# Command-line interface

The BLL and DAL is dependent to run on a file named config.properties (see sample.config.properties), and it has the following default values:

```
## Database related settings
DB_TYPE=mysql
DB_HOST=localhost
DB_NAME=temDocs
DB_USER=sqluser
DB_PASSWORD=sqluserpw

## Indexing related settings
ID_DEFAULT_FOLDER_TO_MONITOR=~/EnronDataSet/1000/,~/Enron/DataSet/10000
ID_EXTENSION=.txt,.doc
```

The _Indexing related settings_ accept a comma separated list, but currently only taking the first folder to monitor.

The BLL will warn you via command line if the config values could not be loaded, therefore you will get a chance to set these settings via command line before running, but the DAL layer does not care - it will throw an error if something's wrong.

How to use the CLI:

```
--- Projects/Search-Indexer ‹feature-config-file* M?› » search-indexer -help
usage: search-indexer
 -dbhost <arg>   Set database hostname, eg. localhost
 -dbname <arg>   Set database name
 -dbpass <arg>   Set the password for the database connection
 -dbtype <arg>   Set database type, eg. mysql
 -dbuser <arg>   Set the username for the database connection
 -help           Prints this message
 -run <arg>      Run the indexing with a given path
 -showsettings   Print current settings
--- Projects/Search-Indexer ‹feature-config-file* M?› » cat config.properties
cat: config.properties: No such file or directory
--- Projects/Search-Indexer ‹feature-config-file* M?› » search-indexer -dbtype mysql -dbname temDocs -dbhost localhost -dbuser sqluser -dbpass sqluserpw
Setting the database type...
Setting the database hostname...
Setting the database name...
Setting the database username...
Setting the database password...
--- Projects/Search-Indexer ‹feature-config-file* M?› » cat config.properties
DB_TYPE = mysql
DB_HOSTNAME = localhost
DB_NAME = temDocs
DB_USER = sqluser
DB_PASS = sqluserpw
ID_DEFAULT_FOLDER_TO_MONITOR =
ID_EXTENSION = .txt
--- Projects/Search-Indexer ‹feature-config-file* M?› » search-indexer -run ~/EnronDataSet/1000
Starting indexing: /Users/anthonymonori/EnronDataSet/1000
Total execution time: 0 minutes for 1000 files.
```

Make sure you add an alias as a shortcut to make the command line cleaner:

```
alias search-indexer='java -jar ~/Projects/Search-Indexer/out/artifacts/Search_Indexer_jar/Search-Indexer.jar'
```

### CODE REVIEW

**Comment by anthonymonori** [comment]
Okay, I'll continue to work on this PR, implementing the CLI, as it is dependent on this one and noone gave a thumbs up to integrate with master.

**Comment by anthonymonori** [comment]
#### At this point please re-import the whole solution into your IDE due to renaming, refactoring!

**Comment by hass123uk** [comment]
Looking good @anthonymonori. Didn't have the chance to look over the changes in order to comment or give a thumps up until now.

**Comment by anthonymonori** [comment]
Properly merged with latest HEAD

**Comment by anthonymonori** [comment]
I'm going to merge this with the master so we can start unit testing around it. If there's any issues with it, please open an Issue.

**Pull request merged**
